[project]
name = "pidforeducation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.3",
    "pygame>=2.6.1",
    "pygame-widgets>=1.1.7",
    "pygbag>=0.9.2",
    "pyinstaller>=6.12.0",
]
