[project]
name = "pidforeducation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flet>=0.27.4",
    "flet-desktop>=0.27.4",
    "numpy>=2.2.3",
    "pillow>=11.1.0",
    "pygame>=2.6.1",
]
